TarifDefterim.UI/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TarifDefterim.Model.Option;
using TarifDefterim.Service.Option;

namespace TarifDefterim.UI.Controllers
{
    public class CategoryController : Controller
    {

        CategoryService _categoryService;

        public CategoryController()
        {
            _categoryService = new CategoryService();
        }

        [ChildActionOnly]
        public ActionResult GetActiveCategory()
        {

            List<Category> categoryList = _categoryService.GetActive();

            return PartialView("_version_1_Menu_Category_List", categoryList);

        }
        

    }
}

TarifDefterim.UI/Controllers/MealController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TarifDefterim.Core.Enum;
using TarifDefterim.Model.Option;
using TarifDefterim.Service.Option;
using TarifDefterim.UI.Models.VM;
using TarifDefterim.Utility;

namespace TarifDefterim.UI.Controllers
{
    public class MealController : Controller
    {

        MealService _mealService;
        MealImageService _mealImage;
        AppUserService _appUserService;
        AssignedCategoryService _assignedCategoryService;

        public MealController()
        {
            _mealService = new MealService();
            _mealImage = new MealImageService();
            _appUserService = new AppUserService();
            _assignedCategoryService = new AssignedCategoryService();
        }

        //Bu metot PartialView'i yönlendirmek için kullanılıyor. ChildActionOnly bu action'ın sadece bu durumlarda çağırılabileceğini belirtir.Opsiyoneldir... 
        [ChildActionOnly]
        public ActionResult GetSliderContent()
        {

            List<Meal> mealList = new List<Meal>();
            mealList = _mealService.GetSliderMeals().OrderByDescending(x => x.CreatedDate).ToList();

            List<MealVM> modelList = new List<MealVM>();

            foreach (var item in mealList)
            {
                MealVM model = new MealVM();
                model.ID = item.ID;
                model.Name = item.Name;
                model.Description = item.Description;
                model.Slug = item.Slug;
                model.PreparationTime = item.PreparationTime;
                model.PreparationTimeUnitOf = item.PreparationTimeUnitOf;
                model.CookingTime = item.CookingTime;
                model.CookingTimeUnitOf = item.CookingTimeUnitOf;
                model.Person = item.Person;
                model.Tricks = item.Tricks;
                model.VideoURL = item.VideoURL;

                AppUser user = _appUserService.TakeMealCreatetorFullName(item.AppUser.UserName);

                model.FullName = user.Name + " " + user.LastName;
                model.AssignedCategories = _assignedCategoryService.GetByExp(x => x.MealID == model.ID && x.Status == Status.Active);

                MealImage mImage = _mealImage.TakeFirstMealImagePath(item.ID);

                if (mImage == null)
                {
                    model.RandomImagePath = ImageUploader.DefaultMealImagePath;
                }
                else
                {
                    model.RandomImagePath = mImage.ImageURL;
                }

                modelList.Add(model);
            }

            return PartialView("_version_1_Slider", modelList);
        }

        [ChildActionOnly]
        public ActionResult GetMealContent(int page=1)
        {

            List<Meal> mealList = new List<Meal>();
            mealList = _mealService.GetSliderMeals().OrderByDescending(x => x.CreatedDate).ToList();

            List<MealVM> modelList = new List<MealVM>();

            foreach (var item in mealList)
            {
                MealVM model = new MealVM();
                model.ID = item.ID;
                model.Name = item.Name;
                model.Description = item.Description;
                model.Slug = item.Slug;
                model.PreparationTime = item.PreparationTime;
                model.PreparationTimeUnitOf = item.PreparationTimeUnitOf;
                model.CookingTime = item.CookingTime;
                model.CookingTimeUnitOf = item.CookingTimeUnitOf;
                model.Person = item.Person;
                model.Tricks = item.Tricks;
                model.VideoURL = item.VideoURL;

                MealImage mImage = _mealImage.TakeFirstMealImagePath(item.ID);

                if (mImage == null)
                {
                    model.RandomImagePath = ImageUploader.DefaultMealImagePath;
                }
                else
                {
                    model.RandomImagePath = mImage.ImageURL;
                }

                modelList.Add(model);
            }

            return PartialView("_version_1_MealList", modelList.ToPagedList(page,6));

        }

        [ChildActionOnly]
        public ActionResult GetRandomMeal()
        {
            
            List<Meal> randomMealList = _mealService.GetActive().Take(5).ToList();

            List<MealVM> mealList = new List<MealVM>();

            foreach (var item in randomMealList)
            {
                MealVM model = new MealVM();
                model.ID = item.ID;
                model.Name = item.Name;
                model.Description = item.Description;
                model.Slug = item.Slug;
                model.PreparationTime = item.PreparationTime;
                model.PreparationTimeUnitOf = item.PreparationTimeUnitOf;
                model.CookingTime = item.CookingTime;
                model.CookingTimeUnitOf = item.CookingTimeUnitOf;
                model.Person = item.Person;
                model.Tricks = item.Tricks;
                model.VideoURL = item.VideoURL;

                MealImage mImage = _mealImage.TakeFirstMealImagePath(item.ID);

                if (mImage == null)
                {
                    model.RandomImagePath = ImageUploader.DefaultMealImagePath;
                }
                else
                {
                    model.RandomImagePath = mImage.CruptedMealImage;
                }

                mealList.Add(model);
            }


            return PartialView("_version_1_Footer", mealList);

        }

        [ChildActionOnly]
        public ActionResult GetPopularMeal()
        {

            List<Meal> randomMealList = _mealService.GetActive().Take(5).ToList();

            List<MealVM> mealList = new List<MealVM>();

            foreach (var item in randomMealList)
            {
                MealVM model = new MealVM();
                model.ID = item.ID;
                model.Name = item.Name;
                model.Description = item.Description;
                model.Slug = item.Slug;
                model.PreparationTime = item.PreparationTime;
                model.PreparationTimeUnitOf = item.PreparationTimeUnitOf;
                model.CookingTime = item.CookingTime;
                model.CookingTimeUnitOf = item.CookingTimeUnitOf;
                model.Person = item.Person;
                model.Tricks = item.Tricks;
                model.VideoURL = item.VideoURL;

                MealImage mImage = _mealImage.TakeFirstMealImagePath(item.ID);

                if (mImage == null)
                {
                    model.RandomImagePath = ImageUploader.DefaultMealImagePath;
                }
                else
                {
                    model.RandomImagePath = mImage.ImageURL;
                }

                mealList.Add(model);
            }


            return PartialView("_version_1_Right_Column", mealList);

        }

    }
}

TarifDefterim.UI/Controllers/RecipeController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TarifDefterim.Core.Enum;
using TarifDefterim.Model.Option;
using TarifDefterim.Service.Option;
using TarifDefterim.UI.Models.VM;
using TarifDefterim.Utility;

namespace TarifDefterim.UI.Controllers
{
    public class RecipeController : Controller
    {
        
        MealService _mealService;
        MealImageService _mealImage;
        FoodIngredientService _foodIngredient;
        RecipeService _recipeService;
        CommentService _commentService;
        CategoryService _categoryService;
        AssignedCategoryService _assignedCategoryService;

        public RecipeController()
        {
            _mealService = new MealService();
            _mealImage = new MealImageService();
            _foodIngredient = new FoodIngredientService();
            _recipeService = new RecipeService();
            _commentService = new CommentService();
            _categoryService = new CategoryService();
            _assignedCategoryService = new AssignedCategoryService();
        }
        
        public ActionResult Index()
        {
            return View();
        }


        
        public ActionResult RecipeDetail(string slug)
        {

            Meal meal = _mealService.GetMealDetail(slug);

            MealVM model = new MealVM();
            model.ID = meal.ID;
            model.Name = meal.Name;
            model.Description = meal.Description;
            model.Slug = meal.Slug;
            model.PreparationTime = meal.PreparationTime;
            model.PreparationTimeUnitOf = meal.PreparationTimeUnitOf;
            model.CookingTime = meal.CookingTime;
            model.CookingTimeUnitOf = meal.CookingTimeUnitOf;
            model.Person = meal.Person;
            model.Tricks = meal.Tricks;
            model.VideoURL = meal.VideoURL;

            List<MealImage> mealImageList = _mealImage.GetByExp(x => x.MealID == meal.ID && x.Status == Status.Active);

            if (mealImageList.Count != 0)
            {
                model.MealImages = mealImageList;

                MealImage mImage = _mealImage.TakeFirstMealImagePath(meal.ID);
                model.RandomImagePath = mImage.ImageURL;
            }
            else
            {
                model.RandomImagePath = ImageUploader.DefaultMealImagePath;
            }

            //List<FoodIngredient> foodIngredientList = _foodIngredient.GetByExp(x => x.MealID == meal.ID && x.Status == Status.Active);            

            model.FoodIngredients = _foodIngredient.GetByExp(x => x.MealID == meal.ID && x.Status == Status.Active);

            List<Recipe> recipeList = _recipeService.GetByExp(x => x.MealID == meal.ID && x.Status == Status.Active).OrderBy(x => x.Alignment).ToList();

            model.Recipes = recipeList;

            model.Comments = _commentService.GetByExp(x => x.MealID == meal.ID && x.Status == Status.Active);

            return View(model);
        }

        [ChildActionOnly]
        public ActionResult GetMealContent(int page = 1)
        {

            List<Meal> mealList = new List<Meal>();

            mealList = _mealService.GetActive().OrderByDescending(x => x.CreatedDate).ToList();


            List<MealVM> modelList = new List<MealVM>();

            foreach (var item in mealList)
            {
                MealVM model = new MealVM();
                model.ID = item.ID;
                model.Name = item.Name;
                model.Description = item.Description;
                model.Slug = item.Slug;
                model.PreparationTime = item.PreparationTime;
                model.PreparationTimeUnitOf = item.PreparationTimeUnitOf;
                model.CookingTime = item.CookingTime;
                model.CookingTimeUnitOf = item.CookingTimeUnitOf;
                model.Person = item.Person;
                model.Tricks = item.Tricks;
                model.VideoURL = item.VideoURL;

                MealImage mImage = _mealImage.TakeFirstMealImagePath(item.ID);

                if (mImage == null)
                {
                    model.RandomImagePath = ImageUploader.DefaultMealImagePath;
                }
                else
                {
                    model.RandomImagePath = mImage.ImageURL;
                }

                modelList.Add(model);
            }

            // ToPagetList kullanmak için NuGet Package Manager`dan PagetList referanslara eklenir.

            return PartialView("_version_1_RecipePage_MealList", modelList.ToPagedList(page, 6));

        }

        public ActionResult AddRecipe()
        {
            return View();
        }
        

        public ActionResult GetMealListByCategory(string categorySlug, int page = 1)
        {

            Category category = _categoryService.GetCategoryIdBySlug(categorySlug);

            List<Meal> mealList = new List<Meal>();

            mealList = _mealService.GetActive().OrderByDescending(x => x.CreatedDate).ToList();

            List<AssignedCategory> assignedCategory = _assignedCategoryService.GetByExp(x => x.CategoryID == category.ID);

            List<MealVM> modelList = new List<MealVM>();

            foreach (var item in mealList)
            {
                foreach (var item2 in assignedCategory)
                {
                    if (item.ID == item2.MealID)
                    {

                        MealVM model = new MealVM();
                        model.ID = item.ID;
                        model.Name = item.Name;
                        model.Description = item.Description;
                        model.Slug = item.Slug;
                        model.PreparationTime = item.PreparationTime;
                        model.PreparationTimeUnitOf = item.PreparationTimeUnitOf;
                        model.CookingTime = item.CookingTime;
                        model.CookingTimeUnitOf = item.CookingTimeUnitOf;
                        model.Person = item.Person;
                        model.Tricks = item.Tricks;
                        model.VideoURL = item.VideoURL;

                        MealImage mImage = _mealImage.TakeFirstMealImagePath(item.ID);

                        if (mImage == null)
                        {
                            model.RandomImagePath = ImageUploader.DefaultMealImagePath;
                        }
                        else
                        {
                            model.RandomImagePath = mImage.ImageURL;
                        }

                        modelList.Add(model);

                    }
                }
            }

            // ToPagetList kullanmak için NuGet Package Manager`dan PagetList referanslara eklenir.

            return View(modelList.ToPagedList(page, 6));

        }


    }
}

TarifDefterim.UI/Controllers/SubscriberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TarifDefterim.Model.Option;
using TarifDefterim.Service.Option;

namespace TarifDefterim.UI.Controllers
{
    public class SubscriberController : Controller
    {

        SubscriberService _subscriberService;

        public SubscriberController()
        {
            _subscriberService = new SubscriberService();
        }

        public JsonResult AddSubscriber(string email)
        {

            Subscriber subscriber = new Subscriber();
            subscriber.Email = email;

            try
            {

                if (!_subscriberService.IsExistMail(email))
                {
                    _subscriberService.Add(subscriber);
                    return Json("Kayıt işlemi başarılı.", JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json("Girilen mail daha önceden kayıtlıdır.", JsonRequestBehavior.AllowGet);
                }
                
            }
            catch (Exception ex)
            {
                return Json("Empty", JsonRequestBehavior.AllowGet);
            }            
        }
    }
}

TarifDefterim.UI/Views/Shared/_version_1_Footer.cshtml
<div id="footer">
    <!-- Container -->
    <div class="container">
        <div class="five columns">
            <!-- Headline -->
            <h3 class="headline footer">Hakkında</h3>
            <span class="line"></span>
            <div class="clearfix"></div>
            <p>TarifDefterim bir girişim projesidir.</p>
        </div>
        <div class="three columns">
            <!-- Headline -->
            <h3 class="headline footer">Menuler</h3>
            <span class="line"></span>
            <div class="clearfix"></div>
            <ul class="footer-links">
                <li><a href="/">Anasayfa</a></li>
                <li><a href="/About/">Hakkında</a></li>
                <li><a href="/Recipe/">Tarifler</a></li>
                <li><a href="/Contact">İletişim</a></li>
                @if (!User.Identity.IsAuthenticated)
                {
                    <li><a href="/Home/Login">Üye Girişi</a></li>
                }
            </ul>
        </div>
        <div class="three columns">
            <!-- Headline -->
            <h3 class="headline footer">Rasgele Tarif</h3>
            <span class="line"></span>
            <div class="clearfix"></div>
            <ul class="footer-links">
                @model IEnumerable<TarifDefterim.UI.Models.VM.MealVM>
                
                @foreach (var item in Model)
                {
                    <li><a href="/Recipe/RecipeDetail/@item.Slug">@item.Name</a></li>
                }
            </ul>
        </div>
        <div class="five columns">
            <!-- Headline -->
            <h3 class="headline footer">Haber Bülteni</h3>
            <span class="line"></span>
            <div class="clearfix"></div>
            <p>Her gün yeni bir lezzetten haber almak için bültene abone olmayı unutmayınız.</p>
                <input class="newsletter" type="text" id="subscriberemail" name="subscriberemail" placeholder="ornek@mail.com" value="" />
                <input class="newsletter-btn" type="button" name="addsubscriber" id="subscriberform" value="Abone Ol" onclick="AddSubscriber()" />
            <span id="subscribermessage"style="display:none"></span>
        </div>
    </div>
    <!-- Container / End -->
</div>

<script>

        function AddSubscriber() {

            var email = $("#subscriberemail").val();
            console.log(email);

            if (email != "") {

                $.ajax({

                    url: "@Url.Action("AddSubscriber", "Subscriber")",
                    type: "POST",
                    datatype: "Json",
                    data: { email: email },
                    success: function (data) {

                        if (data != "Empty") {
                            $("#subscribermessage").html("");
                            $("#subscribermessage").removeAttr("style");
                            $("#subscribermessage").append(data).fadeIn(3000);
                            $("#subscribermessage").fadeOut(10000);
                        }
                        else {
                            $("#subscribermessage").html("");
                            $("#subscribermessage").removeAttr("style");
                            $("#subscribermessage").append(data).fadeIn(3000);
                            $("#subscribermessage").fadeOut(10000);
                        }

                    }

                })
            }

        }

</script>

TarifDefterim.UI/Views/Shared/_version_1_Layout.cshtml
<!DOCTYPE html>
<!--[if IE 8 ]><html class="ie ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!-->
<html lang="tr">
 <!--<![endif]-->
<head>
    <!-- Basic Page Needs
    ================================================== -->
    <meta charset="utf-8" />
    <title>tarifdefterim | CMS</title>
    <meta content="yeme,içme,tarif" name="description" />
    <meta content="Gökhan ÖZGÜR" name="author" />
    <!-- Mobile Specific Metas
    ================================================== -->
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <!-- CSS
    ================================================== -->
    <link href="~/Content/css/version_1/style.css" rel="stylesheet" />
    <link href="~/Content/css/version_1/colors/green.css" rel="stylesheet" />

    <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Wrapper -->    
    <div id="wrapper">

        <!-- Header
        ================================================== -->
        <header id="header">
            <!-- Container -->
            <div class="container">
                <!-- Logo / Mobile Menu -->
                <div class="three columns">
                    <div id="logo">
                        <h1><a href="/">tarifdefterim</a></h1>
                    </div>
                </div>

                <!-- Navigation
                ================================================== -->
                <div class="thirteen columns navigation">
                    <nav id="navigation" class="menu nav-collapse">
                        <ul>
                            <li><a href="/" id="current">Anasayfa</a></li>
                            <li><a href="/About/">Hakkında</a></li>
                            <li>
                                <a href="/Recipe/">Tarifler</a>
                                <ul>
                                    @{
                                        Html.RenderAction("GetActiveCategory", "Category", new { area = "" });
                                    }
                                </ul>                                
                                @if (User.Identity.IsAuthenticated)
                                {
                                <ul>
                                    <li><a href="/Recipe/AddRecipe">Tarif Ekle</a></li>
                                </ul>
                                }
                            </li>                           
                            @*<li><a href="/Contact">İletişim</a></li>*@
                            @if (User.Identity.IsAuthenticated)
                            {
                                <li>
                                    <a href="/AppUser/Profile">@User.Identity.Name</a>
                                    <ul>
                                        <li><a href="/AppUser/Profile">Profilim</a></li>
                                        <li><a href="/Home/Logout">Çıkış</a></li>
                                    </ul>
                                </li>
                            }
                            @if (!User.Identity.IsAuthenticated)
                            {
                                <li><a href="/Home/Login">Üye Girişi</a></li>
                            }
                        </ul>
                    </nav>
                </div>
            </div>
            <!-- Container / End -->
        </header>

        @RenderBody()

        <div class="margin-top-5"></div>        

    </div>
    <!-- Wrapper / End -->
    <!-- Footer
    ================================================== -->
    @{
        Html.RenderAction("GetRandomMeal", "Meal", new { area = "" });
    }
    <!-- Footer / End -->
    <!-- Footer Bottom / Start -->
    <div id="footer-bottom">
        <!-- Container -->
        <div class="container">
            <div class="eight columns">© Copyright 2017 - @DateTime.Now.Year <a href="http://www.gokhanozgur.com">Gökhan ÖZGÜR</a>. Tüm hakları saklıdır.</div>
        </div>
        <!-- Container / End -->
    </div>
    <!-- Footer Bottom / End -->
    <!-- Back To Top Button -->
    <div id="backtotop"><a href="#"></a></div>

    <!-- Java Script
    ================================================== -->
    <script src="~/Content/js/version_1/jquery-1.11.0.min.js"></script>
    <script src="~/Content/js/version_1/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/Content/js/version_1/jquery.superfish.js"></script>
    <script src="~/Content/js/version_1/jquery.royalslider.min.js"></script>
    <script src="~/Content/js/version_1/responsive-nav.js"></script>
    <script src="~/Content/js/version_1/hoverIntent.js"></script>
    <script src="~/Content/js/version_1/isotope.pkgd.min.js"></script>
    <script src="~/Content/js/version_1/chosen.jquery.min.js"></script>
    <script src="~/Content/js/version_1/jquery.tooltips.min.js"></script>
    <script src="~/Content/js/version_1/jquery.magnific-popup.min.js"></script>
    <script src="~/Content/js/version_1/jquery.pricefilter.js"></script>
    <script src="~/Content/js/version_1/custom.js"></script>

    @RenderSection("script",false)



        


</body>
</html>

TarifDefterim.UI/Views/Shared/_version_1_MealList.cshtml
@using PagedList;
@using PagedList.Mvc
@model IPagedList<TarifDefterim.UI.Models.VM.MealVM>

<!-- Isotope -->
<div class="isotope">

    @foreach (var item in Model)
    {
        <div class="four recipe-box columns">
            <!-- Thumbnail -->
            <div class="thumbnail-holder">
                <a href="/Recipe/RecipeDetail/@item.Slug">
                    <img src="@item.RandomImagePath" alt="" />
                    <div class="hover-cover"></div>
                    <div class="hover-icon">Tarifi</div>
                </a>
            </div>
            <!-- Content -->
            <div class="recipe-box-content">
                <h3><a href="/Recipe/RecipeDetail/@item.Slug">@item.Name</a></h3>
                <div class="recipe-meta"><i class="fa fa-clock-o"></i> Hazırlanış @item.PreparationTime @item.PreparationTimeUnitOf</div>
                <div class="recipe-meta"><i class="fa fa-clock-o"></i> Pişirme @item.CookingTime @item.CookingTimeUnitOf</div>
                <div class="clearfix"></div>
            </div>
        </div>
    }

</div>

<div class="clearfix"></div>
<!-- Pagination -->
<div class="pagination-container masonry">
    <nav class="pagination">
            @Html.PagedListPager(Model, page => Url.Action("Index", "Home", new { page }), PagedListRenderOptions.PageNumbersOnly)

    </nav>
</div>
    

TarifDefterim.UI/Views/Shared/_version_1_Menu_Category_List.cshtml
@model List<TarifDefterim.Model.Option.Category>

@foreach (var item in Model)
{
    <li><a href="/Recipe/GetMealListByCategory/@item.Slug">@item.CategoryName</a></li>
}

TarifDefterim.UI/Views/Shared/_version_1_RecipePage_MealList.cshtml
@using PagedList;
@using PagedList.Mvc
@model IPagedList<TarifDefterim.UI.Models.VM.MealVM>

<!-- Isotope -->
<div class="isotope">

    @foreach (var item in Model)
    {
        <div class="four recipe-box columns">
            <!-- Thumbnail -->
            <div class="thumbnail-holder">
                <a href="/Recipe/RecipeDetail/@item.Slug">
                    <img src="@item.RandomImagePath" alt="" />
                    <div class="hover-cover"></div>
                    <div class="hover-icon">Tarifi</div>
                </a>
            </div>
            <!-- Content -->
            <div class="recipe-box-content">
                <h3><a href="/Recipe/RecipeDetail/@item.Slug">@item.Name</a></h3>
                <div class="recipe-meta"><i class="fa fa-clock-o"></i> Hazırlanış @item.PreparationTime @item.PreparationTimeUnitOf</div>
                <div class="recipe-meta"><i class="fa fa-clock-o"></i> Pişirme @item.CookingTime @item.CookingTimeUnitOf</div>
                <div class="clearfix"></div>
            </div>
        </div>
    }

</div>

<div class="clearfix"></div>
<!-- Pagination -->
<div class="pagination-container masonry">
    <nav class="pagination">
        @Html.PagedListPager(Model, page => Url.Action("Index", "Recipe", new { page }), PagedListRenderOptions.PageNumbersOnly)

    </nav>
</div>

TarifDefterim.UI/Views/Shared/_version_1_Right_Column.cshtml
<!-- Sidebar
    ================================================== -->
<div class="four columns">
    <!-- Search Form -->
    <div class="widget search-form">
        <nav class="search">
            <form action="#" method="get">
                <button><i class="fa fa-search"></i></button>
                <input class="search-field" type="text" placeholder="Search for recipes" value="" />
            </form>
        </nav>
        <div class="clearfix"></div>
    </div>

    <!-- Popular Recipes -->
    <div class="widget">
        <h4 class="headline">Popüler Tarifler</h4>
        <span class="line margin-bottom-30"></span>
        <div class="clearfix"></div>


        @model IEnumerable<TarifDefterim.UI.Models.VM.MealVM>

        @foreach (var item in Model)
        {
            <a href="/Recipe/RecipeDetail/@item.Slug" class="featured-recipe">
                <img src="@item.RandomImagePath" alt="">
                <div class="featured-recipe-content">
                    <h4>@item.Name</h4>
                </div>
                <div class="post-icon"></div>
            </a>
        }

        <div class="clearfix"></div>
    </div>
</div>

TarifDefterim.UI/Views/Shared/_version_1_Slider.cshtml
@model IEnumerable<TarifDefterim.UI.Models.VM.MealVM>

<!-- Slider
        ================================================== -->
<div id="homeSlider" class="royalSlider rsDefaultInv">
    @foreach (var item in Model)
    {
        <div class="rsContent">
            <a class="rsImg" href="@item.RandomImagePath"></a>
            <i class="rsTmb">@item.Name</i>
            <!-- Slide Caption -->
            <div class="SlideTitleContainer rsABlock">
                <div class="CaptionAlignment">
                    <div class="rsSlideTitle tags">
                        <ul>
                            @foreach (var c in item.AssignedCategories)
                            {
                                <li>@c.Category.CategoryName</li>
                            }
                        </ul>
                        <div class="clearfix"></div>
                    </div>
                    <h2 class="rsSlideTitle title"><a href="/Recipe/RecipeDetail/@item.Slug">@item.Name</a></h2>
                    <div class="rsSlideTitle details">
                        <ul>
                            <li><i class="fa fa-cutlery"></i> @item.Person kişilik</li>
                            <li><i class="fa fa-clock-o"></i> Hazırlanış @item.PreparationTime @item.PreparationTimeUnitOf</li>
                            <li><i class="fa fa-clock-o"></i> Pişirme @item.CookingTime @item.CookingTimeUnitOf</li>
                            <li><i class="fa fa-user"></i><a href="#"> @item.FullName</a> TARİFİ</li>
                        </ul>
                    </div>
                    <a href="/Recipe/RecipeDetail/@item.Slug" class="rsSlideTitle button">Tarifi Göster</a>
                </div>
            </div>
        </div>

    }    
</div>